name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Angular app
      - name: Build
        run: |
          npm install -g @angular/cli@19
          ng build --configuration=production --base-href "/payroll-demo/"

      # Deploy to gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
