name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [main] # Triggers on push to main branch

# Grant write permissions to the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Angular app
      - name: Build
        run: |
          npm install -g @angular/cli@19
          ng build --configuration=production --base-href "/payroll-demo/"

      # Create 404.html for GitHub Pages routing
      - name: Create 404 Page
        run: cp dist/browser/index.html dist/browser/404.html

      # Deploy to gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Deploys to gh-pages branch
          folder: dist/browser # Folder to deploy
